### ISSUE TITLE
dmidecode command error on Docker

### ISSUE THREAD

**Issue by yangpu** [es128/serial-number#5]
I have tested serial-number works on Ubuntu and Windows, however, it raise an error on Docker:

`
/usr/local/lib/node_modules/serial-number/bin/serial-number:20
        if (err) throw err;
                 ^

Error: Command failed: dmidecode -t system | grep Serial
/dev/mem: No such file or directory

```
at ChildProcess.exithandler (child_process.js:202:12)
at emitTwo (events.js:100:13)
at ChildProcess.emit (events.js:185:7)
at maybeClose (internal/child_process.js:850:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
```

`

**Comment by es128** [comment]
What OS are you running in Docker? Can you point to a free/open docker image that exhibits the issue?

Not all Linux distros bundle dmidecode by default. You may need to install it.

**Comment by techterbium** [comment]
I am facing this issue when trying to npm install on bitbucket's pipeline. As pipelines are run on ubuntu based docker's, how can this be addressed?

**Comment by SDAdham** [comment]
Same here, I am getting the following error which results in yarn install fail in gitlab pipeline:
```
➤ YN0000: │ serial-number@npm:1.3.0 STDERR Could not read serial number: Error: Command failed: dmidecode -t system | grep Serial
➤ YN0000: │ serial-number@npm:1.3.0 STDERR /bin/sh: 1: dmidecode: not found
➤ YN0000: │ serial-number@npm:1.3.0 STDERR 
➤ YN0000: │ serial-number@npm:1.3.0 STDERR     at ChildProcess.exithandler (node:child_process:397:12)
➤ YN0000: │ serial-number@npm:1.3.0 STDERR     at ChildProcess.emit (node:events:394:28)
➤ YN0000: │ serial-number@npm:1.3.0 STDERR     at maybeClose (node:internal/child_process:1067:16)
➤ YN0000: │ serial-number@npm:1.3.0 STDERR     at Socket.<anonymous> (node:internal/child_process:453:11)
➤ YN0000: │ serial-number@npm:1.3.0 STDERR     at Socket.emit (node:events:394:28)
➤ YN0000: │ serial-number@npm:1.3.0 STDERR     at Pipe.<anonymous> (node:net:672:12) {
➤ YN0000: │ serial-number@npm:1.3.0 STDERR   killed: false,
➤ YN0000: │ serial-number@npm:1.3.0 STDERR   code: 1,
➤ YN0000: │ serial-number@npm:1.3.0 STDERR   signal: null,
➤ YN0000: │ serial-number@npm:1.3.0 STDERR   cmd: 'dmidecode -t system | grep Serial'
➤ YN0000: │ serial-number@npm:1.3.0 STDERR }
```
